/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service
 * API for Customer Service
 *
 * The version of the OpenAPI document: 1.23.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AddressJsonldContractInfosReadDocumentationContextOneOf
 */
export interface AddressJsonldContractInfosReadDocumentationContextOneOf {
    [key: string]: any;

    /**
     * 
     * @type {string}
     * @memberof AddressJsonldContractInfosReadDocumentationContextOneOf
     */
    '@vocab': string;
    /**
     * 
     * @type {string}
     * @memberof AddressJsonldContractInfosReadDocumentationContextOneOf
     */
    'hydra': AddressJsonldContractInfosReadDocumentationContextOneOfHydraEnum;
}

export const AddressJsonldContractInfosReadDocumentationContextOneOfHydraEnum = {
    HttpWwwW3OrgNsHydraCore: 'http://www.w3.org/ns/hydra/core#'
} as const;

export type AddressJsonldContractInfosReadDocumentationContextOneOfHydraEnum = typeof AddressJsonldContractInfosReadDocumentationContextOneOfHydraEnum[keyof typeof AddressJsonldContractInfosReadDocumentationContextOneOfHydraEnum];


