/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service
 * API for Customer Service
 *
 * The version of the OpenAPI document: 1.23.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ContractContractEditDocumentation
 */
export interface ContractContractEditDocumentation {
    /**
     * 
     * @type {string}
     * @memberof ContractContractEditDocumentation
     */
    'contractNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContractContractEditDocumentation
     */
    'type'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ContractContractEditDocumentation
     */
    'enabled'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ContractContractEditDocumentation
     */
    'locked'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ContractContractEditDocumentation
     */
    'externalId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContractContractEditDocumentation
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContractContractEditDocumentation
     */
    'lastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContractContractEditDocumentation
     */
    'updateDateAt'?: string | null;
}

