/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service
 * API for Customer Service
 *
 * The version of the OpenAPI document: 1.23.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ContractContractReadByTokenDocumentation } from './contract-contract-read-by-token-documentation';

/**
 * 
 * @export
 * @interface ContractContractCollectionContractReadByTokenDocumentation
 */
export interface ContractContractCollectionContractReadByTokenDocumentation {
    /**
     * 
     * @type {Array<ContractContractReadByTokenDocumentation>}
     * @memberof ContractContractCollectionContractReadByTokenDocumentation
     */
    'data'?: Array<ContractContractReadByTokenDocumentation>;
}

