/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service
 * API for Customer Service
 *
 * The version of the OpenAPI document: 1.23.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ContractInfosContractContractInfosReadDocumentation
 */
export interface ContractInfosContractContractInfosReadDocumentation {
    /**
     * 
     * @type {object}
     * @memberof ContractInfosContractContractInfosReadDocumentation
     */
    'address'?: object;
    /**
     * Gets id.
     * @type {string}
     * @memberof ContractInfosContractContractInfosReadDocumentation
     */
    'id'?: string | null;
    /**
     * Gets uuid.
     * @type {string}
     * @memberof ContractInfosContractContractInfosReadDocumentation
     */
    'uuid'?: string | null;
    /**
     * Gets contract_number.
     * @type {string}
     * @memberof ContractInfosContractContractInfosReadDocumentation
     */
    'contractNumber'?: string | null;
    /**
     * Gets brand.
     * @type {string}
     * @memberof ContractInfosContractContractInfosReadDocumentation
     */
    'brand'?: string | null;
    /**
     * Gets account_active.
     * @type {boolean}
     * @memberof ContractInfosContractContractInfosReadDocumentation
     */
    'accountActive'?: boolean | null;
    /**
     * Gets civility.
     * @type {number}
     * @memberof ContractInfosContractContractInfosReadDocumentation
     */
    'civility'?: number | null;
    /**
     * Gets email.
     * @type {string}
     * @memberof ContractInfosContractContractInfosReadDocumentation
     */
    'email'?: string | null;
    /**
     * Gets first_name.
     * @type {string}
     * @memberof ContractInfosContractContractInfosReadDocumentation
     */
    'firstName'?: string | null;
    /**
     * Gets last_name.
     * @type {string}
     * @memberof ContractInfosContractContractInfosReadDocumentation
     */
    'lastName'?: string | null;
    /**
     * Gets language_code.
     * @type {string}
     * @memberof ContractInfosContractContractInfosReadDocumentation
     */
    'languageCode'?: string | null;
    /**
     * Gets id_client.
     * @type {string}
     * @memberof ContractInfosContractContractInfosReadDocumentation
     */
    'idClient'?: string | null;
    /**
     * Gets birth_date.
     * @type {string}
     * @memberof ContractInfosContractContractInfosReadDocumentation
     */
    'birthDate'?: string | null;
    /**
     * 
     * @type {object}
     * @memberof ContractInfosContractContractInfosReadDocumentation
     */
    'contractCreationDate'?: object;
    /**
     * Gets phone_number.
     * @type {string}
     * @memberof ContractInfosContractContractInfosReadDocumentation
     */
    'phoneNumber'?: string | null;
    /**
     * Gets creation_date.
     * @type {string}
     * @memberof ContractInfosContractContractInfosReadDocumentation
     */
    'creationDate'?: string | null;
    /**
     * Gets package.
     * @type {string}
     * @memberof ContractInfosContractContractInfosReadDocumentation
     */
    'package'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ContractInfosContractContractInfosReadDocumentation
     */
    'generalCondition'?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof ContractInfosContractContractInfosReadDocumentation
     */
    'contractDocument'?: string;
}

