/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service
 * API for Customer Service
 *
 * The version of the OpenAPI document: 1.23.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AddressJsonldContractInfosReadDocumentationContext } from './address-jsonld-contract-infos-read-documentation-context';

/**
 * 
 * @export
 * @interface ContractJsonldContractEditDocumentation
 */
export interface ContractJsonldContractEditDocumentation {
    /**
     * 
     * @type {AddressJsonldContractInfosReadDocumentationContext}
     * @memberof ContractJsonldContractEditDocumentation
     */
    '@context'?: AddressJsonldContractInfosReadDocumentationContext;
    /**
     * 
     * @type {string}
     * @memberof ContractJsonldContractEditDocumentation
     */
    '@id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContractJsonldContractEditDocumentation
     */
    '@type'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContractJsonldContractEditDocumentation
     */
    'contractNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContractJsonldContractEditDocumentation
     */
    'type'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ContractJsonldContractEditDocumentation
     */
    'enabled'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ContractJsonldContractEditDocumentation
     */
    'locked'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ContractJsonldContractEditDocumentation
     */
    'externalId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContractJsonldContractEditDocumentation
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContractJsonldContractEditDocumentation
     */
    'lastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContractJsonldContractEditDocumentation
     */
    'updateDateAt'?: string | null;
}

