/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service
 * API for Customer Service
 *
 * The version of the OpenAPI document: 1.23.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetContractCollection200ResponseHydraSearchHydraMappingInner } from './get-contract-collection200-response-hydra-search-hydra-mapping-inner';

/**
 * 
 * @export
 * @interface GetContractCollection200ResponseHydraSearch
 */
export interface GetContractCollection200ResponseHydraSearch {
    /**
     * 
     * @type {string}
     * @memberof GetContractCollection200ResponseHydraSearch
     */
    '@type'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetContractCollection200ResponseHydraSearch
     */
    'hydra:template'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetContractCollection200ResponseHydraSearch
     */
    'hydra:variableRepresentation'?: string;
    /**
     * 
     * @type {Array<GetContractCollection200ResponseHydraSearchHydraMappingInner>}
     * @memberof GetContractCollection200ResponseHydraSearch
     */
    'hydra:mapping'?: Array<GetContractCollection200ResponseHydraSearchHydraMappingInner>;
}

