/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service
 * API for Customer Service
 *
 * The version of the OpenAPI document: 1.23.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ContractJsonldContractReadDocumentation } from './contract-jsonld-contract-read-documentation';
// May contain unused imports in some cases
// @ts-ignore
import { GetContractCollection200ResponseHydraSearch } from './get-contract-collection200-response-hydra-search';
// May contain unused imports in some cases
// @ts-ignore
import { GetContractCollection200ResponseHydraView } from './get-contract-collection200-response-hydra-view';

/**
 * 
 * @export
 * @interface GetContractCollection200Response
 */
export interface GetContractCollection200Response {
    /**
     * 
     * @type {Array<ContractJsonldContractReadDocumentation>}
     * @memberof GetContractCollection200Response
     */
    'hydra:member': Array<ContractJsonldContractReadDocumentation>;
    /**
     * 
     * @type {number}
     * @memberof GetContractCollection200Response
     */
    'hydra:totalItems'?: number;
    /**
     * 
     * @type {GetContractCollection200ResponseHydraView}
     * @memberof GetContractCollection200Response
     */
    'hydra:view'?: GetContractCollection200ResponseHydraView;
    /**
     * 
     * @type {GetContractCollection200ResponseHydraSearch}
     * @memberof GetContractCollection200Response
     */
    'hydra:search'?: GetContractCollection200ResponseHydraSearch;
}

