/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service
 * API for Customer Service
 *
 * The version of the OpenAPI document: 1.23.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OfferServiceCodeOutputOfferServiceCodeDocumentation
 */
export interface OfferServiceCodeOutputOfferServiceCodeDocumentation {
    /**
     * 
     * @type {boolean}
     * @memberof OfferServiceCodeOutputOfferServiceCodeDocumentation
     */
    'success'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof OfferServiceCodeOutputOfferServiceCodeDocumentation
     */
    'httpStatus'?: number;
    /**
     * 
     * @type {string}
     * @memberof OfferServiceCodeOutputOfferServiceCodeDocumentation
     */
    'code'?: string;
    /**
     * 
     * @type {string}
     * @memberof OfferServiceCodeOutputOfferServiceCodeDocumentation
     */
    'beginValidityDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof OfferServiceCodeOutputOfferServiceCodeDocumentation
     */
    'endValidityDate'?: string;
}

