/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service
 * API for Customer Service
 *
 * The version of the OpenAPI document: 1.23.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OfferActivateOfferInputActivateOfferDocumentation
 */
export interface OfferActivateOfferInputActivateOfferDocumentation {
    /**
     * 
     * @type {string}
     * @memberof OfferActivateOfferInputActivateOfferDocumentation
     */
    'brand'?: string;
    /**
     * 
     * @type {string}
     * @memberof OfferActivateOfferInputActivateOfferDocumentation
     */
    'contractNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof OfferActivateOfferInputActivateOfferDocumentation
     */
    'typeContract'?: string;
    /**
     * 
     * @type {string}
     * @memberof OfferActivateOfferInputActivateOfferDocumentation
     */
    'packageName'?: string;
    /**
     * 
     * @type {string}
     * @memberof OfferActivateOfferInputActivateOfferDocumentation
     */
    'languageCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof OfferActivateOfferInputActivateOfferDocumentation
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof OfferActivateOfferInputActivateOfferDocumentation
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof OfferActivateOfferInputActivateOfferDocumentation
     */
    'category'?: string;
    /**
     * 
     * @type {string}
     * @memberof OfferActivateOfferInputActivateOfferDocumentation
     */
    'refContract'?: string;
    /**
     * 
     * @type {string}
     * @memberof OfferActivateOfferInputActivateOfferDocumentation
     */
    'typeAdvantage'?: string;
    /**
     * 
     * @type {Array<File>}
     * @memberof OfferActivateOfferInputActivateOfferDocumentation
     */
    'attachments'?: Array<File>;
    /**
     * 
     * @type {string}
     * @memberof OfferActivateOfferInputActivateOfferDocumentation
     */
    'amount': string;
    /**
     * 
     * @type {string}
     * @memberof OfferActivateOfferInputActivateOfferDocumentation
     */
    'purchaseAmount'?: string;
    /**
     * 
     * @type {string}
     * @memberof OfferActivateOfferInputActivateOfferDocumentation
     */
    'purchaseDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof OfferActivateOfferInputActivateOfferDocumentation
     */
    'currency'?: string;
    /**
     * 
     * @type {string}
     * @memberof OfferActivateOfferInputActivateOfferDocumentation
     */
    'amountType'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OfferActivateOfferInputActivateOfferDocumentation
     */
    'iban'?: string | null;
}

