/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service
 * API for Customer Service
 *
 * The version of the OpenAPI document: 1.23.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AddressJsonldContractInfosReadDocumentationContext } from './address-jsonld-contract-infos-read-documentation-context';
// May contain unused imports in some cases
// @ts-ignore
import { OfferItemOutputJsonldOfferConsumedExpiredDocumentation } from './offer-item-output-jsonld-offer-consumed-expired-documentation';

/**
 * 
 * @export
 * @interface OfferOfferOutputJsonldOfferConsumedExpiredDocumentation
 */
export interface OfferOfferOutputJsonldOfferConsumedExpiredDocumentation {
    /**
     * 
     * @type {AddressJsonldContractInfosReadDocumentationContext}
     * @memberof OfferOfferOutputJsonldOfferConsumedExpiredDocumentation
     */
    '@context'?: AddressJsonldContractInfosReadDocumentationContext;
    /**
     * 
     * @type {string}
     * @memberof OfferOfferOutputJsonldOfferConsumedExpiredDocumentation
     */
    '@id'?: string;
    /**
     * 
     * @type {string}
     * @memberof OfferOfferOutputJsonldOfferConsumedExpiredDocumentation
     */
    '@type'?: string;
    /**
     * []
     * @type {Array<OfferItemOutputJsonldOfferConsumedExpiredDocumentation>}
     * @memberof OfferOfferOutputJsonldOfferConsumedExpiredDocumentation
     */
    'offers'?: Array<OfferItemOutputJsonldOfferConsumedExpiredDocumentation>;
}

