/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service
 * API for Customer Service
 *
 * The version of the OpenAPI document: 1.23.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { OfferItemOutputOfferConsumedExpiredDocumentation } from './offer-item-output-offer-consumed-expired-documentation';

/**
 * 
 * @export
 * @interface OfferOfferOutputOfferConsumedExpiredDocumentation
 */
export interface OfferOfferOutputOfferConsumedExpiredDocumentation {
    /**
     * []
     * @type {Array<OfferItemOutputOfferConsumedExpiredDocumentation>}
     * @memberof OfferOfferOutputOfferConsumedExpiredDocumentation
     */
    'offers'?: Array<OfferItemOutputOfferConsumedExpiredDocumentation>;
}

