/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service
 * API for Customer Service
 *
 * The version of the OpenAPI document: 1.23.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OfferFujifilmSsoInputUserFujifilmSessionDocumentation
 */
export interface OfferFujifilmSsoInputUserFujifilmSessionDocumentation {
    /**
     * 
     * @type {string}
     * @memberof OfferFujifilmSsoInputUserFujifilmSessionDocumentation
     */
    'sessionKey'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OfferFujifilmSsoInputUserFujifilmSessionDocumentation
     */
    'brand': string | null;
    /**
     * 
     * @type {string}
     * @memberof OfferFujifilmSsoInputUserFujifilmSessionDocumentation
     */
    'contractNumber': string | null;
    /**
     * 
     * @type {string}
     * @memberof OfferFujifilmSsoInputUserFujifilmSessionDocumentation
     */
    'login': string | null;
    /**
     * 
     * @type {string}
     * @memberof OfferFujifilmSsoInputUserFujifilmSessionDocumentation
     */
    'partnerName': string | null;
    /**
     * 
     * @type {string}
     * @memberof OfferFujifilmSsoInputUserFujifilmSessionDocumentation
     */
    'typeContract': string | null;
    /**
     * 
     * @type {string}
     * @memberof OfferFujifilmSsoInputUserFujifilmSessionDocumentation
     */
    'packageName': string | null;
    /**
     * 
     * @type {string}
     * @memberof OfferFujifilmSsoInputUserFujifilmSessionDocumentation
     */
    'languageCode': string | null;
}

