/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service
 * API for Customer Service
 *
 * The version of the OpenAPI document: 1.23.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OfferFavoriteShopOfferOutputActivateOfferDocumentation
 */
export interface OfferFavoriteShopOfferOutputActivateOfferDocumentation {
    /**
     * 
     * @type {string}
     * @memberof OfferFavoriteShopOfferOutputActivateOfferDocumentation
     */
    'offerId'?: string;
    /**
     * 
     * @type {string}
     * @memberof OfferFavoriteShopOfferOutputActivateOfferDocumentation
     */
    'cardNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof OfferFavoriteShopOfferOutputActivateOfferDocumentation
     */
    'amount'?: string;
}

