/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service
 * API for Customer Service
 *
 * The version of the OpenAPI document: 1.23.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OfferItemOutputOfferFavoriteGiftAvailableDocumentation
 */
export interface OfferItemOutputOfferFavoriteGiftAvailableDocumentation {
    /**
     * 
     * @type {string}
     * @memberof OfferItemOutputOfferFavoriteGiftAvailableDocumentation
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof OfferItemOutputOfferFavoriteGiftAvailableDocumentation
     */
    'offerUuidBappli'?: string;
    /**
     * 
     * @type {string}
     * @memberof OfferItemOutputOfferFavoriteGiftAvailableDocumentation
     */
    'contractNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof OfferItemOutputOfferFavoriteGiftAvailableDocumentation
     */
    'cardNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof OfferItemOutputOfferFavoriteGiftAvailableDocumentation
     */
    'expiration'?: string;
    /**
     * 
     * @type {number}
     * @memberof OfferItemOutputOfferFavoriteGiftAvailableDocumentation
     */
    'amount'?: number;
    /**
     * 
     * @type {string}
     * @memberof OfferItemOutputOfferFavoriteGiftAvailableDocumentation
     */
    'state'?: string;
    /**
     * 
     * @type {string}
     * @memberof OfferItemOutputOfferFavoriteGiftAvailableDocumentation
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof OfferItemOutputOfferFavoriteGiftAvailableDocumentation
     */
    'category'?: string;
    /**
     * 
     * @type {string}
     * @memberof OfferItemOutputOfferFavoriteGiftAvailableDocumentation
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof OfferItemOutputOfferFavoriteGiftAvailableDocumentation
     */
    'updatedAt'?: string;
}

