/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service
 * API for Customer Service
 *
 * The version of the OpenAPI document: 1.23.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AddressJsonldContractInfosReadDocumentationContext } from './address-jsonld-contract-infos-read-documentation-context';

/**
 * 
 * @export
 * @interface OfferItemOutputJsonldOfferFavoriteGiftAvailableDocumentation
 */
export interface OfferItemOutputJsonldOfferFavoriteGiftAvailableDocumentation {
    /**
     * 
     * @type {AddressJsonldContractInfosReadDocumentationContext}
     * @memberof OfferItemOutputJsonldOfferFavoriteGiftAvailableDocumentation
     */
    '@context'?: AddressJsonldContractInfosReadDocumentationContext;
    /**
     * 
     * @type {string}
     * @memberof OfferItemOutputJsonldOfferFavoriteGiftAvailableDocumentation
     */
    '@id'?: string;
    /**
     * 
     * @type {string}
     * @memberof OfferItemOutputJsonldOfferFavoriteGiftAvailableDocumentation
     */
    '@type'?: string;
    /**
     * 
     * @type {string}
     * @memberof OfferItemOutputJsonldOfferFavoriteGiftAvailableDocumentation
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof OfferItemOutputJsonldOfferFavoriteGiftAvailableDocumentation
     */
    'offerUuidBappli'?: string;
    /**
     * 
     * @type {string}
     * @memberof OfferItemOutputJsonldOfferFavoriteGiftAvailableDocumentation
     */
    'contractNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof OfferItemOutputJsonldOfferFavoriteGiftAvailableDocumentation
     */
    'cardNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof OfferItemOutputJsonldOfferFavoriteGiftAvailableDocumentation
     */
    'expiration'?: string;
    /**
     * 
     * @type {number}
     * @memberof OfferItemOutputJsonldOfferFavoriteGiftAvailableDocumentation
     */
    'amount'?: number;
    /**
     * 
     * @type {string}
     * @memberof OfferItemOutputJsonldOfferFavoriteGiftAvailableDocumentation
     */
    'state'?: string;
    /**
     * 
     * @type {string}
     * @memberof OfferItemOutputJsonldOfferFavoriteGiftAvailableDocumentation
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof OfferItemOutputJsonldOfferFavoriteGiftAvailableDocumentation
     */
    'category'?: string;
    /**
     * 
     * @type {string}
     * @memberof OfferItemOutputJsonldOfferFavoriteGiftAvailableDocumentation
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof OfferItemOutputJsonldOfferFavoriteGiftAvailableDocumentation
     */
    'updatedAt'?: string;
}

