/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service
 * API for Customer Service
 *
 * The version of the OpenAPI document: 1.23.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProductSwapProductSwapInputProductSwapCreateDocumentation
 */
export interface ProductSwapProductSwapInputProductSwapCreateDocumentation {
    /**
     * 
     * @type {number}
     * @memberof ProductSwapProductSwapInputProductSwapCreateDocumentation
     */
    'declarationId': number | null;
    /**
     * 
     * @type {string}
     * @memberof ProductSwapProductSwapInputProductSwapCreateDocumentation
     */
    'brand': string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductSwapProductSwapInputProductSwapCreateDocumentation
     */
    'contractNumber': string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductSwapProductSwapInputProductSwapCreateDocumentation
     */
    'packageName': string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductSwapProductSwapInputProductSwapCreateDocumentation
     */
    'typeAdvantage': string | null;
}

