/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service
 * API for Customer Service
 *
 * The version of the OpenAPI document: 1.23.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProductSwapProductSwapOutputProductSwapReadDocumentation
 */
export interface ProductSwapProductSwapOutputProductSwapReadDocumentation {
    /**
     * 
     * @type {number}
     * @memberof ProductSwapProductSwapOutputProductSwapReadDocumentation
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductSwapProductSwapOutputProductSwapReadDocumentation
     */
    'offerUuidBappli'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductSwapProductSwapOutputProductSwapReadDocumentation
     */
    'contractNumber'?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductSwapProductSwapOutputProductSwapReadDocumentation
     */
    'productDeclaration'?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductSwapProductSwapOutputProductSwapReadDocumentation
     */
    'registrationDate'?: string | null;
}

