/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service
 * API for Customer Service
 *
 * The version of the OpenAPI document: 1.23.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProductDeclarationProductDeclarationReadDocumentation
 */
export interface ProductDeclarationProductDeclarationReadDocumentation {
    /**
     * 
     * @type {string}
     * @memberof ProductDeclarationProductDeclarationReadDocumentation
     */
    'type': string;
    /**
     * 
     * @type {string}
     * @memberof ProductDeclarationProductDeclarationReadDocumentation
     */
    'brand': string;
    /**
     * 
     * @type {string}
     * @memberof ProductDeclarationProductDeclarationReadDocumentation
     */
    'model': string;
    /**
     * 
     * @type {string}
     * @memberof ProductDeclarationProductDeclarationReadDocumentation
     */
    'purchaseInvoice'?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProductDeclarationProductDeclarationReadDocumentation
     */
    'productDetails'?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof ProductDeclarationProductDeclarationReadDocumentation
     */
    'contract'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ProductDeclarationProductDeclarationReadDocumentation
     */
    'id'?: number;
}

