/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service
 * API for Customer Service
 *
 * The version of the OpenAPI document: 1.23.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AddressJsonldContractInfosReadDocumentationContext } from './address-jsonld-contract-infos-read-documentation-context';

/**
 * 
 * @export
 * @interface UserHubsideWebSsoInputJsonldUserHubsideWebSessionDocumentation
 */
export interface UserHubsideWebSsoInputJsonldUserHubsideWebSessionDocumentation {
    /**
     * 
     * @type {AddressJsonldContractInfosReadDocumentationContext}
     * @memberof UserHubsideWebSsoInputJsonldUserHubsideWebSessionDocumentation
     */
    '@context'?: AddressJsonldContractInfosReadDocumentationContext;
    /**
     * 
     * @type {string}
     * @memberof UserHubsideWebSsoInputJsonldUserHubsideWebSessionDocumentation
     */
    '@id'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserHubsideWebSsoInputJsonldUserHubsideWebSessionDocumentation
     */
    '@type'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserHubsideWebSsoInputJsonldUserHubsideWebSessionDocumentation
     */
    'brand': string | null;
    /**
     * 
     * @type {string}
     * @memberof UserHubsideWebSsoInputJsonldUserHubsideWebSessionDocumentation
     */
    'contractNumber': string | null;
    /**
     * 
     * @type {string}
     * @memberof UserHubsideWebSsoInputJsonldUserHubsideWebSessionDocumentation
     */
    'login': string | null;
    /**
     * 
     * @type {string}
     * @memberof UserHubsideWebSsoInputJsonldUserHubsideWebSessionDocumentation
     */
    'partnerName': string | null;
    /**
     * 
     * @type {string}
     * @memberof UserHubsideWebSsoInputJsonldUserHubsideWebSessionDocumentation
     */
    'typeContract': string | null;
    /**
     * 
     * @type {string}
     * @memberof UserHubsideWebSsoInputJsonldUserHubsideWebSessionDocumentation
     */
    'packageName': string | null;
    /**
     * 
     * @type {string}
     * @memberof UserHubsideWebSsoInputJsonldUserHubsideWebSessionDocumentation
     */
    'languageCode': string | null;
}

