/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service
 * API for Customer Service
 *
 * The version of the OpenAPI document: 1.23.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserUserSendSmsRequestInputUserSendSmsAccountDocumentation
 */
export interface UserUserSendSmsRequestInputUserSendSmsAccountDocumentation {
    /**
     * 
     * @type {string}
     * @memberof UserUserSendSmsRequestInputUserSendSmsAccountDocumentation
     */
    'confirmationToken': string | null;
    /**
     * 
     * @type {string}
     * @memberof UserUserSendSmsRequestInputUserSendSmsAccountDocumentation
     */
    'contractNumber': string | null;
}

