/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service
 * API for Customer Service
 *
 * The version of the OpenAPI document: 1.23.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserContractSubscribeRequestInputUserSubscribeDocumentation
 */
export interface UserContractSubscribeRequestInputUserSubscribeDocumentation {
    /**
     * 
     * @type {string}
     * @memberof UserContractSubscribeRequestInputUserSubscribeDocumentation
     */
    'contractNumber': string | null;
    /**
     * 
     * @type {string}
     * @memberof UserContractSubscribeRequestInputUserSubscribeDocumentation
     */
    'product': string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UserContractSubscribeRequestInputUserSubscribeDocumentation
     */
    'enabled': boolean | null;
    /**
     * 
     * @type {string}
     * @memberof UserContractSubscribeRequestInputUserSubscribeDocumentation
     */
    'externalId': string | null;
}

