/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service
 * API for Customer Service
 *
 * The version of the OpenAPI document: 1.23.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AddressJsonldContractInfosReadDocumentationContext } from './address-jsonld-contract-infos-read-documentation-context';
// May contain unused imports in some cases
// @ts-ignore
import { ContractJsonldUserReadDocumentation } from './contract-jsonld-user-read-documentation';

/**
 * 
 * @export
 * @interface UserJsonldUserReadDocumentation
 */
export interface UserJsonldUserReadDocumentation {
    /**
     * 
     * @type {string}
     * @memberof UserJsonldUserReadDocumentation
     */
    '@id'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserJsonldUserReadDocumentation
     */
    '@type'?: string;
    /**
     * 
     * @type {AddressJsonldContractInfosReadDocumentationContext}
     * @memberof UserJsonldUserReadDocumentation
     */
    '@context'?: AddressJsonldContractInfosReadDocumentationContext;
    /**
     * 
     * @type {string}
     * @memberof UserJsonldUserReadDocumentation
     */
    'brand'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserJsonldUserReadDocumentation
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserJsonldUserReadDocumentation
     */
    'lastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserJsonldUserReadDocumentation
     */
    'username'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserJsonldUserReadDocumentation
     */
    'enabled'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UserJsonldUserReadDocumentation
     */
    'languageCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserJsonldUserReadDocumentation
     */
    'countryCode'?: string;
    /**
     * 
     * @type {Array<ContractJsonldUserReadDocumentation>}
     * @memberof UserJsonldUserReadDocumentation
     */
    'contracts'?: Array<ContractJsonldUserReadDocumentation>;
    /**
     * 
     * @type {number}
     * @memberof UserJsonldUserReadDocumentation
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof UserJsonldUserReadDocumentation
     */
    'creationDateAt'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserJsonldUserReadDocumentation
     */
    'updateDateAt'?: string | null;
}

