/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service
 * API for Customer Service
 *
 * The version of the OpenAPI document: 1.23.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserUserEditDocumentation
 */
export interface UserUserEditDocumentation {
    /**
     * 
     * @type {string}
     * @memberof UserUserEditDocumentation
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUserEditDocumentation
     */
    'lastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUserEditDocumentation
     */
    'username'?: string;
}

