/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service
 * API for Customer Service
 *
 * The version of the OpenAPI document: 1.23.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserUserUpdateEmailRequestInputUserUpdateEmailUserChangePasswordDocumentation
 */
export interface UserUserUpdateEmailRequestInputUserUpdateEmailUserChangePasswordDocumentation {
    /**
     * 
     * @type {string}
     * @memberof UserUserUpdateEmailRequestInputUserUpdateEmailUserChangePasswordDocumentation
     */
    'newPassword'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUserUpdateEmailRequestInputUserUpdateEmailUserChangePasswordDocumentation
     */
    'confirmPassword'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUserUpdateEmailRequestInputUserUpdateEmailUserChangePasswordDocumentation
     */
    'smsCode': string;
}

