# ================================================
# !!! @ansible - DO NOT EDIT THIS FILE LOCALLY !!!
# ================================================

FROM registry.idx.ovh/nginx:front-bullseye

RUN mkdir /var/www/html/public --parent
ADD --chown=www-data:www-data dist /var/www/html/public

RUN /enable-entrypoint.sh vue-to-config-js 50
